apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: "mysc"
  resources:
    requests:
      storage: 1Gi
